name: Publish release

on:
  push:
    tags:
      - 'v*' # On push events with tags matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools wheel twine

    - name: Build
      run: python -m build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build package
        path: dist/

    # - name: Publish to PyPI
    #   env:
    #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
    #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    #   run: twine upload dist/*

    # - name: Create GitHub Release
    #   uses: ncipollo/release-action@v1
    #   with:
    #     name: Release ${{ github.ref }}
    #     tag: ${{ github.ref }}
    #     artifacts: "dist/"
    #     body: |
    #       Changes in this Release
    #     token: ${{ secrets.GITHUB_TOKEN }}
